remote_theme: emilbaehr/automatic-app-landing-page
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Save The Nick!
description: Description
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]

collections:
  docs:
    output: true
